version: 2

.openssh_job: &opensshjob
  docker:
    - image: ${IMAGE}
  steps:
    - checkout
    - run:
        name: Set up SSH environment
        command: |
          mkdir -p -m 0755 /var/empty
          groupadd sshd
          useradd -g sshd -c 'sshd privsep' -d /var/empty -s /bin/false sshd
    - run:
        name: Clone liboqs
        command: .circleci/git_no_checkin_in_last_day.sh || (./oqs-scripts/clone_liboqs.sh)
    - run:
        name: Build liboqs
        command: .circleci/git_no_checkin_in_last_day.sh || (./oqs-scripts/build_liboqs.sh)
    - run:
        name: Build OpenSSH
        command: .circleci/git_no_checkin_in_last_day.sh || (./oqs-scripts/build_openssh.sh)
    - run:
        name: Run unit tests
        command: mkdir -p test-results && .circleci/git_no_checkin_in_last_day.sh || (python3 -m nose --rednose --verbose --with-xunit --xunit-file=test-results/nosetests.xml)
    - store_test_results: # Note that this command will fail when running CircleCI locally, that is expected behaviour
        path: test-results

jobs:
  # amd64-buster (Debian 10)
  debian-buster-amd64-with-openssl-with-pqauth:
    <<: *opensshjob
    environment:
      IMAGE: openquantumsafe/ci-debian-buster-amd64:latest
      ARCH: x64
      WITH_OPENSSL: true
      WITH_PQAUTH: true
  debian-buster-amd64-with-openssl-no-pqauth:
    <<: *opensshjob
    environment:
      IMAGE: openquantumsafe/ci-debian-buster-amd64:latest
      ARCH: x64
      WITH_OPENSSL: true
      WITH_PQAUTH: false
  debian-buster-amd64-no-openssl-no-pqauth:
    <<: *opensshjob
    environment:
      IMAGE: openquantumsafe/ci-debian-buster-amd64:latest
      ARCH: x64
      WITH_OPENSSL: false
      WITH_PQAUTH: false
  # x86_64-bionic (Ubuntu 18.04)
  ubuntu-bionic-x86_64-with-openssl-with-pqauth:
    <<: *opensshjob
    environment:
      IMAGE: openquantumsafe/ci-ubuntu-bionic-x86_64:latest
      ARCH: x64
      WITH_OPENSSL: true
      WITH_PQAUTH: true
  ubuntu-bionic-x86_64-with-openssl-no-pqauth:
    <<: *opensshjob
    environment:
      IMAGE: openquantumsafe/ci-ubuntu-bionic-x86_64:latest
      ARCH: x64
      WITH_OPENSSL: true
      WITH_PQAUTH: false
  ubuntu-bionic-x86_64-no-openssl-no-pqauth:
    <<: *opensshjob
    environment:
      IMAGE: openquantumsafe/ci-ubuntu-bionic-x86_64:latest
      ARCH: x64
      WITH_OPENSSL: false
      WITH_PQAUTH: false

workflows:
  version: 2
  build:
    jobs:
      - debian-buster-amd64-with-openssl-with-pqauth
      - debian-buster-amd64-with-openssl-no-pqauth
      - debian-buster-amd64-no-openssl-no-pqauth
      - ubuntu-bionic-x86_64-with-openssl-with-pqauth
      - ubuntu-bionic-x86_64-with-openssl-no-pqauth
      - ubuntu-bionic-x86_64-no-openssl-no-pqauth
  nightly:
    triggers:
      - schedule:
          cron: "0 2 * * *"
          filters:
            branches:
              only:
                - OQS-master
    jobs:
      - debian-buster-amd64-with-openssl-with-pqauth
      - debian-buster-amd64-with-openssl-no-pqauth
      - debian-buster-amd64-no-openssl-no-pqauth
      - ubuntu-bionic-x86_64-with-openssl-with-pqauth
      - ubuntu-bionic-x86_64-with-openssl-no-pqauth
      - ubuntu-bionic-x86_64-no-openssl-no-pqauth
